#
# This is the Travis-CI configuration.
#

language: "python"

# This is how you get container-based environments on Travis-CI.  And
# container-based environments are how you get fast test runs.
sudo: false

# Only build master; for "push" builds, this is when the branch pushed
# to is master, for "pr" builds, this is when the merge base of the PR
# is master.
branches:
  only:
    - master

cache:
  directories:
    # Cache the pip download cache across runs to avoid having to
    # repeatedly download packages over the network.
    - "$HOME/.cache/pip"

# A special travis-based way to say that we need some additional OS
# packages.  These are required to build pyOpenSSL, on which txAWS
# depends.
addons:
  apt:
    packages:
    - "libssl-dev"
    - "libssl1.0.0"

env:
  global:
    # travis encrypt -r twisted/txaws TXAWS_INTEGRATION_AWS_ACCESS_KEY_ID=...
    # Or: docker run --rm --name travisci caktux/travis-cli encrypt -r twisted/txaws ...
    - secure: "P4VU87FJM65jN7D36k6usBmkSAht8r2L2TzKMklkiihxFSNqv5lybpsIdAGlr/pQ3FltgUmsHsmbR6EfYJuqr3UsM/06LhmQc5aBj96DmKzonBfDe0q59UETvi5g7XRrIxM3DNvI6Jz29vtqvahddrMW65KxGUZ4/5hMdmdICno="
    # travis encrypt -r twisted/txaws TXAWS_INTEGRATION_AWS_SECRET_ACCESS_KEY=...
    - secure: "LjKE0uLHqohbgSRHTmKBrl9REgXIxHEuIoM43FgdE1cPCncs+1+HBxptmjppP3q6zJ5O3rOMkef+PYa3SfiWODuvxt7n8P9ZZqEt8c7BxQKBMropqw/87P4McFAC0RNjPImQozWG30qH+v3Uq1o1psURUxZPin8pX/U7lJsT40k="

install:
  - "pip install --upgrade pip setuptools wheel coverage codecov"
  # Travis pre-installed attrs screws with pip dependency resolution (not that
  # it takes much...).  Explicitly upgrade attrs here to prevent old version
  # from breaking everything.
  - "pip install --upgrade attrs"
  - "pip install --upgrade .[dev]"

script:
  - "coverage run --rcfile=${PWD}/.coveragerc $(type -p trial) txaws"

after_success:
  - "codecov"

after_script:
  - "test-tools/cleanup-aws"
